apiVersion: apps/v1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: myalias=ghcr.io/vighneshpath/argoprac/micronautguide
    argocd-image-updater.argoproj.io/myalias.update-strategy: latest