apiVersion: v1
kind: Service
metadata:
  name: micronautguide
  annotations:
    argocd-image-updater.argoproj.io/image-list: myalias=ghcr.io/vighneshpath/argoprac/micronautguide
    argocd-image-updater.argoproj.io/myalias.update-strategy: latest
spec:
  ports:
    - port: 8083
      targetPort: 8083
  selector:
    app: micronautguide