apiVersion: apps/v1
kind: Deployment
metadata:
  name: micronautguide
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: micronautguide
  template:
    metadata:
      labels:
        app: micronautguide
    spec:
      containers:
        - image: ghcr.io/vighneshpath/argoprac/micronautguide:0.1.4
          name: micronautguide
          ports:
            - containerPort: 8083
              hostPort: 8083
