apiVersion: apps/v1
kind: Application
project: default
source:
  repoURL: "https://github.com/VighneshPath/ArgoPrac"
  path: argo
  targetRevision: HEAD
destination:
  server: "https://kubernetes.default.svc"
  namespace: default
syncPolicy:
  automated: {}
