on:
  push:
    branches: "main"

jobs:
  build-and-deploy:
    runs-on: ["ubuntu-latest"]
    env:
      REGISTRY_NAME: "ghcr.io"
      REGISTRY_URL: "ghcr.io/vighneshpath/argoprac"

    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3

      - name: Validate gradle
        uses: gradle/wrapper-validation-action@v1

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17.0.1"
          distribution: "temurin"

      - name: Login to docker registry
        run: echo ${{secrets.CR_PAT}} | docker login ghcr.io -u VighneshPath --password-stdin

      - name: Push image to docker registry
        run: ./gradlew dockerPushRegistry

      - uses: imranismail/setup-kustomize@v2
      - run: |
          kustomize edit set image my-app=ghcr.io/vighneshpath/argoprac/micronautguide:${{ github.sha }}
          git add .
          git commit -m "Set `app` image tag to `${{ github.sha }}`"
          git push

      # - name: Push image to docker registry
      #   run: ./gradlew dockerPushLatest
