on:
  push:
    branches: "main"
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ["ubuntu-latest"]
    env:
      REGISTRY_NAME: "ghcr.io"
      REGISTRY_URL: "ghcr.io/vighneshpath/argoprac"

    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3

      - name: Validate gradle
        uses: gradle/wrapper-validation-action@v1

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17.0.1"
          distribution: "temurin"

      - name: Login to docker registry
        run: echo ${{secrets.CR_PAT}} | docker login ghcr.io -u VighneshPath --password-stdin

      - name: Push image to docker registry
        run: ./gradlew dockerPushRegistry

      # - name: Update kustomize
      #   run : |
      #     ./gradlew kustomize
      #     if git diff --exit-code ./kutomize; then
      #         echo "No changes in kustomization.yaml. Skipping commit."
      #     else
      #         echo "Changes detected in kustomization.yaml. Committing..."
      #         git config --global user.email "ci@example.com"  # Set your desired email for the CI/CD bot
      #         git config --global user.name "CI/CD Bot"       # Set your desired username for the CI/CD bot
      #         git add ./kutomize
      #         git commit -m "Update version in kustomization.yaml"
      #         git push
      #     fi

      # - name: Kustomize set
      #   run: |
      #     cd ./kutomize
      #     kustomize edit set image my-app=ghcr.io/vighneshpath/argoprac/micronautguide:0.1.9
      #     git config --global user.email "git@bot.com"
      #     git config --global user.name "Git Bot"
      #     git add .
      #     git commit -m "Set app image tag to 0.1.9"
      #     git push

      # - name: Push image to docker registry
      #   run: ./gradlew dockerPushLatest
