apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: my-app
    newName: ghcr.io/vighneshpath/argoprac/micronautguide
    newTag: 0.1.9

commonAnnotations:
  argocd-image-updater.argoproj.io/image-list: myalias=ghcr.io/vighneshpath/argoprac/micronautguide
  argocd-image-updater.argoproj.io/myalias.update-strategy: semver
