apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: my-app
    newName: ghcr.io/vighneshpath/argoprac/micronautguide
    newTag: 0.1.6

commonAnnotations:
  argocd-image-updater.argoproj.io/image-list: "ghcr.io/vighneshpath/argoprac/micronautguide"
# Add any customizations here, such as common labels, annotations, and patches
# For example:
# commonLabels:
#   app: my-app
# commonAnnotations:
#   description: My Application
# images:
#   - name: ghcr.io/vighneshpath/argoprac/micronautguide
#     newName: ghcr.io/my-organization/my-app
#     newTag: 0.1.5
